name: APK Analysis
run-name: Analysing APK Files
on: [push]
jobs:
    decompile-apk:
        runs-on: ubuntu-22.04
        steps:
            - name: install jq and java-21-jdk
              run: sudo apt update && sudo apt install jq openjdk-21-jdk
            - name: download jadx
              run: |
                    wget $(curl -s https://api.github.com/repos/skylot/jadx/releases/latest |jq '.assets[0].browser_download_url' -r) -O ${{ runner.temp }}/jadx.zip
                    unzip ${{ runner.temp }}/jadx.zip -d ${{ runner.temp }}/jadx
            - name: check jadx
              run: ls ${{ runner.temp }}/jadx
            - name: checkout repo
              uses: actions/checkout@v4
            - name: decompile apk
              run: ${{ runner.temp }}/jadx/bin/jadx -d jadx.out -e -m simple --deobf --use-dx $(ls ${{ github.workspace }}/*.apk)
            - name: list out files
              run: ls -la jadx.out
            - name: zip out files
              run: zip -r apk-decompile.zip jadx.out
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v4
              with:
               name: apk-decompile.zip
               path: apk-decompile.zip